### ISSUE TITLE
[FEAT] Data 전처리

### ISSUE THREAD

**Issue by hsm8867** [SuminHam/final_project#1]
## Background
- API 요청 처리 및 기본적인 모델링

## TODO
- [x] api 요청 코드 추가
- [ ] EDA
- [ ] preprocessing 코드 추가
- [x] modeling 코드 추가
