### ISSUE TITLE
[FEAT] FastAPI 초기 세팅

### ISSUE THREAD

**Issue by hsm8867** [SuminHam/final_project#20]
## Background
- FastAPI 초기 세팅

## TODO
- [x] db에서 데이터 불러오는 작업
- [x] 비동기 데이터베이스 구현
- [x] Redis 구현
- [x] Error Handler 구현
- [x] Middleware 구현
- [x] Dipendency 구현

## SEE also
- https://logan-mle.notion.site/Chapter-2-ec610c78094b4e9eab93af98790bcfec
- https://logan-mle.notion.site/Chapter-3-Error-Handler-Middleware-Dependency-3c49ec0e793349108df4089d97192c5e
