### ISSUE TITLE
[FEAT] code refactoring

### ISSUE THREAD

**Issue by hsm8867** [SuminHam/final_project#53]
## Background
- code refactoring

## TODO
- [x] airflow/ api key 마스킹
- [ ] airflow/ dag 이름 수정
- [ ] 변수 이름 가독성 좋게 수정
- [ ] 레포지토리 분리 (fastapi / ml pipeline)
- [x] utils 환경변수 주입 파트 삭제

## SEE also
- x
